// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AddhobbyController from "./addhobby_controller"
application.register("addhobby", AddhobbyController)

import ChatroomSubscriptionController from "./chatroom_subscription_controller"
application.register("chatroom-subscription", ChatroomSubscriptionController)

import EventhobbyController from "./eventhobby_controller"
application.register("eventhobby", EventhobbyController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import PricebuttonController from "./pricebutton_controller"
application.register("pricebutton", PricebuttonController)

import SavegiftsController from "./savegifts_controller"
application.register("savegifts", SavegiftsController)
